title: Youth Coalition For Alcohol Education
description: Fayette YCAE

url: http://fayetteycae.org
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact

social:
   email: marisafitzgerald@hotmail.com

google_analytics: "UA-72234643-1"
